---
title: "Reprodutibilidade Científica com o R 2024"
format: html
editor: visual
theme: quartz
---

## Giulia Terlecki

## Repositório da disciplina de Reprodutibilidade Científica com o R do PPG em Ambientometria Furg 2024

Este é um repositório produzido na disciplina "Reprodutibilidade de Resultados Cientificos com o R" - Programa de Pós-graduação em Ambientometria da Universidade Federal de Rio Grande - FURG - que propõe a divulgação de métodos e resultados científicos em páginas online de acesso público.

Dentro deste repositório estão páginas, criadas como forma de avaliação da disciplina, relacionadas a diversos temas, principalmente a meu projeto de doutorado pelo Programa de Pós-graduação em Oceanografia Biológica da FURG.

## Principais Tópicos Relacionados à Pesquisa

<a href="pagina1_EcologiaTroficaDeTubaroes.html"style= "color: white;">Ecologia Trofica De Tubaroes</a>

<a href="Métodos de Identificação de Estoques Pesqueiros.html"style= "color: white;">Métodos de Identificação de Estoques Pesqueiros</a>

<a href="Marcadores Químicos na Identificação de Estoques Pesqueiros.html"style= "color: white;">Análises Elementares e Isotópicas na Identificação de Estoques Pesqueiros</a>

## Seleção de Materiais Biológicos a Serem Utilizados nas Análises

<a href="TestesdeInsercoes.html"style= "color: white;">Vértebras para Análises</a>

## Apresentação Simplificada do Projeto de Doutorado

<a href="pptquartoDocGiulia.html"style= "color: white;">Apresentação Projeto de Doutorado Giulia</a>

## Artigo Teste formatado com RMarkdown modelo Elsevier

[Seasonal patterns on isotopic niches and diet of Bigeye and Southern Spotted Opah (Lamprididae) in Southwestern Atlantic Ocean](ArtigoElsevier.pdf)





```{=html}
<style>
        body {
            background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5a5yV00isAjA9ssyqhoYWgleewVZbxjd5Iw&s');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
            padding: 0;
            font-family: Times New Roman, sans-serif;
            color: white;
        }

        .content {
            position: relative;
            width: 100%;
            margin: 0 auto;
            padding: 20px;
            background-color: rgba(0, 0, 0, 0.0); /* Fundo semitransparente */
            border-radius: 10px;
        }
    </style>
```




