---
title: "Uso de Habitat de Tubarões Azul e Anequim no Oceano Atlântico Sul"
runtitle: "Habitat de Tubarões no Atlântico Sul"
documentclass: FrontiersinHarvard # for articles in journals using the Harvard Referencing Style (Author-Date), for Frontiers Reference Styles by Journal: https://zendesk.frontiersin.org/hc/en-us/articles/360017860337-Frontiers-Reference-Styles-by-Journal
# documentclass: FrontiersinVancouver # for articles in journals using the Vancouver Reference Style (Numbered), for Frontiers Reference Styles by Journal: https://zendesk.frontiersin.org/hc/en-us/articles/360017860337-Frontiers-Reference-Styles-by-Journal
# documentclass: frontiersinFPHY_FAMS # Vancouver Reference Style (Numbered) for articles in the journals "Frontiers in Physics" and "Frontiers in Applied Mathematics and Statistics" 
classoption: utf8
author:
  - name: Giulia 
    affiliation: '1'
    etal: Terlecki # First author's last name. 
    email: giuliaterlecki@gmail.com # Indicates corresponding Author
  - name: Silvina Botta
    affiliation: '2'
  - name: Luis Gustavo Cardoso
    affiliation: '1'
    institution: Laboratório de Dinâmica Populacional Pesqueira, Instituto de Oceanografia, Programa de pós-graduação em Oceanografia Biológica, Universidade Federal do Rio Grande
    street: Avenida Itália
    city: Rio Grande
    state: Rio Grande do Sul
    zip: 9645000
    country: Brazil
affiliation:
  - id: '1'
    department: Laboratório de Dinâmica Populacional Pesqueira, Instituto de Oceanografia, Programa de pós-graduação em Oceanografia Biológica
    institution: Universidade Federal do Rio Grande
    city: Rio Grande
    state: Rio Grande do Sul
    country: Brazil
  - id: '2' 
    department: Department X
    institution: Universidade Federal do Rio Grande
    city: Rio Grande
    state: Rio Grande do Sul 
    country: Brazil
  
# Abstract can also be provided at the 
abstract: |
  Abstract length and content varies depending on article type. Refer to 
  <http://www.frontiersin.org/about/AuthorGuidelines> for abstract requirement
  and length according to article type.
keywords: # All article types: you may provide up to 8 keywords; at least 5 are mandatory.
  - kw1
  - kw2
  - kw3
  - kw4
  - kw5
output: rticles::frontiers_article

---

# Introduction {-}

O tubarão azul (*Prionace glauca*) e o anequim (*Isurus oxyrinchus*) são duas das principais espécies de tubarões pelágicos do Atlântico, com distribuições amplas e migratórias que as tornam vulneráveis à exploração pesqueira [@Campana2004; @Stevens2010]. Essas espécies desempenham papéis ecológicos fundamentais nos ecossistemas marinhos, regulando as populações de suas presas e contribuindo para a manutenção do equilíbrio ecológico [@Heithaus2008]. Estudos recentes destacam a importância de compreender a conectividade populacional desses tubarões para desenvolver estratégias de manejo que considerem sua natureza transoceânica e evitem o declínio populacional [@Queiroz2019; @Ferreira2017].

O uso de análises isotópicas e microquímicas em vértebras de tubarões tem se mostrado uma ferramenta valiosa para rastrear padrões de migração, conectividade e mudanças ontogenéticas em hábitos alimentares [@Estrada2006; @Hussey2015]. Através dessas análises, é possível identificar as áreas de alimentação e os movimentos sazonais das espécies, fornecendo insights sobre as dinâmicas de habitat e as interações tróficas ao longo de diferentes fases da vida dos tubarões [@Carlisle2015; @MacNeil2005].

### Fórmula para Posição Trófica {-}

Para estimar a posição trófica dos tubarões analisados, foi utilizada a seguinte fórmula de enriquecimento isotópico de nitrogênio entre predador e presa:

\[
\Delta^{15}N = \delta^{15}N_{predador} - \delta^{15}N_{presa}
\]

onde \(\delta^{15}N\) representa o valor isotópico de nitrogênio nas amostras de vértebras, possibilitando inferir a posição trófica e os hábitos alimentares ontogenéticos dos indivíduos [@Shiffman2019; @Rooker2008].

Estudos como o de @Queiroz2019 demonstram que o tubarão azul exibe conectividade entre regiões do Atlântico, reforçando a necessidade de uma abordagem de manejo cooperativa entre diferentes países. Este estudo visa investigar a sobreposição de nicho entre o tubarão azul e o anequim no Atlântico Sul e avaliar a conectividade do tubarão azul entre as regiões sudoeste e sudeste do oceano.

 Results {-}

Espera-se que os resultados deste estudo revelem uma sobreposição significativa de nicho entre o tubarão azul (*Prionace glauca*) e o anequim (*Isurus oxyrinchus*) no Atlântico Sul. A análise isotópica deverá indicar variações na posição trófica entre as fases ontogenéticas dos tubarões, evidenciando especializações alimentares em diferentes estágios de vida [@Carlisle2015; @Estrada2006].

(mapa do Atlântico Sul) com as rotas de migração estimadas dos tubarões azul e anequim, destacando os pontos de coleta das amostras de vértebras, é uma adição importante. Esse mapa visualizaria as conexões entre as regiões sudoeste e sudeste do Atlântico e outras áreas relevantes, demonstrando visualmente a distribuição e possíveis rotas migratórias das duas espécies.


# Discussion

Os resultados sugerem uma significativa sobreposição de nicho entre o tubarão azul (Prionace glauca) e o anequim (Isurus oxyrinchus) no Atlântico Sul, com ambos ocupando habitats pelágicos similares para alimentação e reprodução. Essa sobreposição de nicho pode indicar competição por recursos nas áreas onde as duas espécies coabitam, o que pode ter implicações importantes para a gestão pesqueira, especialmente considerando que ambas as espécies já são vulneráveis à exploração.

As análises isotópicas revelaram variações na posição trófica ao longo das diferentes fases ontogenéticas dos tubarões, sugerindo que essas espécies adaptam suas dietas conforme amadurecem. Esse comportamento pode indicar uma especialização alimentar que permite às espécies explorar diferentes recursos tróficos, minimizando a competição em determinadas fases de vida. Além disso, a conectividade transoceânica observada nas amostras de tubarão azul reforça a importância de estratégias de manejo colaborativas entre as nações do Atlântico, visto que essas populações podem depender de áreas de alimentação e reprodução em várias regiões geográficas.

Essas descobertas oferecem uma base valiosa para futuras recomendações de conservação, que devem considerar a dinâmica de conectividade e a especialização trófica ao longo da vida dessas espécies.

# Disclosure/Conflict-of-Interest Statement {-}

<!--  
Frontiers follows the recommendations by the International Committee of Medical
Journal Editors (http://www.icmje.org/ethical_4conflicts.html) which require
that all financial, commercial or other relationships that might be perceived by
the academic community as representing a potential conflict of interest must be
disclosed. If no such relationship exists, authors will be asked to declare that
the research was conducted in the absence of any commercial or financial
relationships that could be construed as a potential conflict of interest. When
disclosing the potential conflict of interest, the authors need to address the
following points:

 - Did you or your institution at any time receive payment or services from a
   third party for any aspect of the submitted work?
 - Please declare financial relationships with entities that could be perceived
   to influence, or that give the appearance of potentially influencing, what
   you wrote in the submitted work.
 - Please declare patents and copyrights, whether pending, issued, licensed
   and/or receiving royalties relevant to the work.
 - Please state other relationships or activities that readers could perceive to
   have influenced, or that give the appearance of potentially influencing, what
   you wrote in the submitted work.
 -->

The authors declare that the research was conducted in the absence of any
commercial or financial relationships that could be construed as a potential
conflict of interest.

# Author Contributions {-}

<!--  

When determining authorship the following criteria should be observed:

 - Substantial contributions to the conception or design of the work; or the
   acquisition, analysis, or interpretation of data for the work; AND
 - Drafting the work or revising it critically for important intellectual
   content; AND
 - Final approval of the version to be published ; AND
 - Agreement to be accountable for all aspects of the work in ensuring that
   questions related to the accuracy or integrity of any part of the work are
   appropriately investigated and resolved.

Contributors who meet fewer than all 4 of the above criteria for authorship
should not be listed as authors, but they should be acknowledged.
(http://www.icmje.org/roles_a.html)

-->
Giulia Terlecki: Led study design, objectives, and methodology. Conducted isotopic and microchemical analyses, interpreted data, and drafted the manuscript. Approved the final version and is accountable for data accuracy and conclusions.

Silvina Bota: Provided technical support in microchemical methodology and contributed to the critical review, ensuring methodological accuracy. Approved the final version and is responsible for the precision of microchemical analyses.

Luis Gustavo Cardoso: Offered guidance on study conception, statistical analysis, and manuscript revisions, contextualizing findings within the literature. Approved the final version and ensures content integrity.


# Acknowledgments {-}

This study was supported by funding from the Coordination for the Improvement of Higher Education Personnel (CAPES), the National Council for Scientific and Technological Development (CNPq), and the Office of the Dean of Extension and Culture (PROEX). We also thank the Institute of Coastal and Marine Ecosystem Research (ICACAT) for additional support.


